version: "3"

services:
  serializer-text:

    build:
      context: .
      dockerfile: Dockerfiles/text.Dockerfile
    image: serializer/text:1.0
    container_name: serializer-text
    ports:
      - 5002:5002
    environment:
      - PORT=5002

  serializer-xml:

    build:
      context: .
      dockerfile: Dockerfiles/xml.Dockerfile
    image: serializer/xml:1.0
    container_name: serializer-xml
    ports:
      - 5000:5000
    environment:
      - PORT=5000

  serializer-json:

    build:
      context: .
      dockerfile: Dockerfiles/json.Dockerfile
    image: serializer/json:1.0
    container_name: serializer-json
    ports:
      - 5004:5004
    environment:
      - PORT=5004
  
  serializer-proto:

    build:
      context: .
      dockerfile: Dockerfiles/proto.Dockerfile
    image: serializer/proto:1.0
    container_name: serializer-proto
    ports:
      - 5001:5001
    environment:
      - PORT=5001
  
  serializer-avro:

    build:
      context: .
      dockerfile: Dockerfiles/avro.Dockerfile
    image: serializer/avro:1.0
    container_name: serializer-avro
    ports:
      - 5006:5006
    environment:
      - PORT=5006

  serializer-yaml:

    build:
      context: .
      dockerfile: Dockerfiles/yaml.Dockerfile
    image: serializer/yaml:1.0
    container_name: serializer-yaml
    ports:
      - 5007:5007
    environment:
      - PORT=5007
  
  serializer-msg:

    build:
      context: .
      dockerfile: Dockerfiles/msg.Dockerfile
    image: serializer/msg:1.0
    container_name: serializer-msg
    ports:
      - 5008:5008
    environment:
      - PORT=5008
  
  serializer-proxi:
  
    build:
      context: .
      dockerfile: Dockerfiles/proxy.Dockerfile
    image: serializer/proxy:1.1
    ports:
      - 6000:6000
    environment:
      - PORT=6000
  
  